import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: '✨ 服务器指南',
	  link: {
	    type: 'doc',
		id: 'intro'
	  },
	  items: [
	    '新人必看',
		'服务器条约',
		'服务器特色内容',
		'游戏内指令',
		'常见问题速查',
		'反馈or建议方法',
		'服主有话说',
		'开发有话说',
		'关于赞助',
		'关于我们'
	  ]
      
    },
  ],
   
};

export default sidebars;
